name: Pages

on:
  push:
    branches:
      - main # 或你要监听的分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 检出代码
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 自动身份验证

      - name: Use Node.js 20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Clean Hexo
        run: npx hexo clean

      - name: Generate static site
        run: npx hexo generate

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 令牌
        run: npx hexo deploy
